cannot open file does_not_exist.toml
parse successful
Found table hello in data/simple.toml
No table does_not_exist in data/simple.toml
Found hello at thing
No string at does_not_exist in data/simple.toml
Found array at thing two in data/simple.toml
No array at does_not_exist in data/simple.toml
Found string array at 1
No string at index 2
Found table at 0 at world
No table found at 1
Found key thing at 0
Found key thing two at 1
No key found at 2
